#!/usr/bin/env python3
"""
EIAAW Workforce — MySQL → PostgreSQL schema dump translator.

Reads database/schema/mysql-schema.sql (produced by `php artisan schema:dump
--database=mysql`) and emits database/schema/pgsql-schema.sql, a Postgres-native
baseline that Laravel's `migrate` command will replay on the EIAAW Workforce
SaaS Postgres deployment.

This is deliberately scoped to the patterns ACTUALLY present in the Claritas
schema (no FULLTEXT, no generated columns, no SPATIAL). It is NOT a generic
translator — re-run `php artisan schema:dump` if the source schema changes
materially, then re-run this.

Translation rules applied:
  - Backtick identifiers `foo` → double-quoted "foo"
  - bigint unsigned AUTO_INCREMENT → bigserial / bigint GENERATED BY DEFAULT AS IDENTITY
  - tinyint(1) → boolean (with default mapping '0'→false, '1'→true)
  - int unsigned / bigint unsigned → int / bigint (Postgres has no unsigned;
    we accept the loss of the high bit since Laravel never relies on it)
  - enum('a','b','c') → varchar(255) with a CHECK constraint
  - json → jsonb (Postgres' efficient binary JSON)
  - decimal(p,s) → numeric(p,s)
  - text COLLATE utf8mb4_unicode_ci → text
  - varchar(N) COLLATE utf8mb4_unicode_ci → varchar(N)
  - timestamp NULL DEFAULT NULL → timestamp(0) NULL
  - timestamp DEFAULT CURRENT_TIMESTAMP → timestamp(0) DEFAULT CURRENT_TIMESTAMP
  - ENGINE=InnoDB ... CHARSET=utf8mb4 ... → stripped
  - MySQL-specific /*!40xxx ... */ comments → stripped
  - INSERT INTO migrations preserved verbatim (with backticks → double quotes)
  - PRIMARY KEY / UNIQUE KEY / KEY → translated to PRIMARY KEY / UNIQUE
    constraint / CREATE INDEX statements
  - FOREIGN KEY constraints kept (Postgres syntax compatible)

Usage:
  cd database/schema
  python translate_mysql_to_pgsql.py
"""
from __future__ import annotations

import re
from pathlib import Path

SOURCE = Path(__file__).parent / "mysql-schema.sql"
TARGET = Path(__file__).parent / "pgsql-schema.sql"


def strip_mysql_comments(sql: str) -> str:
    """Remove MySQL conditional /*!40xxx ... */ comment-as-directive blocks
    and the SET @OLD_xxx prelude."""
    sql = re.sub(r"/\*!\d+\s+[^*]*\*/;?\n?", "", sql)
    sql = re.sub(r"/\*!\d+\s+[^*]*\*/", "", sql)
    return sql


def quote_identifiers(sql: str) -> str:
    """Convert backtick identifiers to Postgres double-quoted identifiers."""
    return re.sub(r"`([^`]+)`", r'"\1"', sql)


def translate_column_types(line: str) -> str:
    """Translate per-column type declarations within a CREATE TABLE body."""
    original = line

    # tinyint(1) → boolean — must run BEFORE the generic tinyint rule
    # (without trailing \b — closing paren is not a word char so \b is unreliable)
    line = re.sub(r"\btinyint\(1\)", "boolean", line, flags=re.IGNORECASE)
    # tinyint(N) where N != 1 → smallint (no length on Postgres smallint)
    line = re.sub(r"\btinyint\(\d+\)", "smallint", line, flags=re.IGNORECASE)
    line = re.sub(r"\btinyint\b", "smallint", line, flags=re.IGNORECASE)

    # smallint unsigned / int unsigned / bigint unsigned → drop "unsigned"
    line = re.sub(r"\b(smallint|mediumint|int|bigint)\s+unsigned\b", r"\1", line, flags=re.IGNORECASE)
    # mediumint → integer
    line = re.sub(r"\bmediumint\(\d+\)", "integer", line, flags=re.IGNORECASE)
    line = re.sub(r"\bmediumint\b", "integer", line, flags=re.IGNORECASE)
    # int(N) → integer
    line = re.sub(r"\bint\(\d+\)", "integer", line, flags=re.IGNORECASE)
    line = re.sub(r"\bint\b(?!eger)(?!\w)", "integer", line, flags=re.IGNORECASE)
    # bigint(N) → bigint
    line = re.sub(r"\bbigint\(\d+\)", "bigint", line, flags=re.IGNORECASE)

    # double / float → double precision / real
    line = re.sub(r"\bdouble\s*(\(\d+,\d+\))?\b", "double precision", line, flags=re.IGNORECASE)
    line = re.sub(r"\bfloat\s*(\(\d+,\d+\))?\b", "real", line, flags=re.IGNORECASE)

    # datetime → timestamp(0)
    line = re.sub(r"\bdatetime\b", "timestamp(0)", line, flags=re.IGNORECASE)
    # timestamp without precision → timestamp(0) for parity with MySQL
    line = re.sub(r"\btimestamp\b(?!\()", "timestamp(0)", line, flags=re.IGNORECASE)

    # MySQL YEAR type → Postgres smallint (no native YEAR equivalent)
    # Match the type position only — never matches "year" column NAMES because
    # column names appear in quotes ("year") which the regex won't match.
    line = re.sub(r"(?<![\"_a-zA-Z])\byear\b(?![\"_a-zA-Z(])", "smallint", line, flags=re.IGNORECASE)

    # json → jsonb
    line = re.sub(r"\bjson\b", "jsonb", line, flags=re.IGNORECASE)

    # longtext / mediumtext / tinytext → text
    line = re.sub(r"\b(long|medium|tiny)text\b", "text", line, flags=re.IGNORECASE)

    # CHARACTER SET / COLLATE clauses → strip
    line = re.sub(r"\s+CHARACTER\s+SET\s+\w+", "", line, flags=re.IGNORECASE)
    line = re.sub(r"\s+COLLATE\s+\w+", "", line, flags=re.IGNORECASE)

    # Inline MySQL COMMENT '...' on column → strip (Postgres uses
    # COMMENT ON COLUMN ... IS ... separately; not worth round-tripping for v1)
    line = re.sub(r"\s+COMMENT\s+'(?:[^'\\]|\\.|'')*'", "", line, flags=re.IGNORECASE)

    # AUTO_INCREMENT → handled separately (added to PRIMARY KEY column)
    line = re.sub(r"\s+AUTO_INCREMENT\b", " GENERATED BY DEFAULT AS IDENTITY", line, flags=re.IGNORECASE)

    # Boolean defaults: '0' → false, '1' → true (only after we know it's a boolean)
    if "boolean" in line:
        line = re.sub(r"DEFAULT\s+'0'", "DEFAULT false", line, flags=re.IGNORECASE)
        line = re.sub(r"DEFAULT\s+'1'", "DEFAULT true", line, flags=re.IGNORECASE)

    # numeric default '0' / '0.00' → 0 / 0.00 (postgres accepts unquoted)
    # leave as-is; postgres tolerates string-quoted numeric defaults

    return line


def translate_enum_to_check(table_name: str, column_def: str) -> tuple[str, str | None]:
    """Convert  enum('a','b','c')  to  varchar(255) + CHECK clause.
    Returns (column_def_replaced, check_constraint_or_None)."""
    m = re.search(
        r'(\s+)"([^"]+)"\s+enum\(([^)]+)\)(.*)$',
        column_def,
        flags=re.IGNORECASE,
    )
    if not m:
        return column_def, None
    indent, col_name, enum_values, rest = m.group(1), m.group(2), m.group(3), m.group(4)
    # Generate the CHECK constraint
    check_name = f'"{table_name}_{col_name}_check"'
    check_constraint = f'CONSTRAINT {check_name} CHECK ("{col_name}" IN ({enum_values}))'
    new_def = f'{indent}"{col_name}" varchar(255){rest}'
    return new_def, check_constraint


CREATE_TABLE_RE = re.compile(r'^CREATE TABLE "([^"]+)"\s*\(\s*$', re.IGNORECASE)
PRIMARY_KEY_RE = re.compile(r'^\s*PRIMARY KEY\s*\(([^)]+)\)\s*,?\s*$', re.IGNORECASE)
UNIQUE_KEY_RE  = re.compile(r'^\s*UNIQUE KEY\s+"([^"]+)"\s*\(([^)]+)\)\s*,?\s*$', re.IGNORECASE)
KEY_RE         = re.compile(r'^\s*KEY\s+"([^"]+)"\s*\(([^)]+)\)\s*,?\s*$', re.IGNORECASE)
CONSTRAINT_FK_RE = re.compile(r'^\s*CONSTRAINT\s+"([^"]+)"\s+FOREIGN KEY', re.IGNORECASE)
TABLE_END_RE   = re.compile(r'^\)\s*ENGINE=', re.IGNORECASE)
DROP_TABLE_RE  = re.compile(r'^DROP TABLE IF EXISTS', re.IGNORECASE)
SET_RE         = re.compile(r'^SET\s', re.IGNORECASE)
INSERT_MIGRATIONS_RE = re.compile(r'^INSERT INTO "migrations"', re.IGNORECASE)


def emit_sequence_resync(table_name: str) -> str:
    """Emit a SELECT setval() that re-aligns a table's IDENTITY sequence to
    MAX(id) + 1 after explicit-ID inserts. Postgres' GENERATED IDENTITY columns
    use a system sequence named "<table>_<column>_seq" by default."""
    return (
        f'SELECT setval(pg_get_serial_sequence(\'"{table_name}"\', \'id\'), '
        f'COALESCE((SELECT MAX("id") FROM "{table_name}"), 1));'
    )


def translate(source_sql: str) -> str:
    """Top-level translation orchestrator.

    Walks the source SQL line-by-line. For each CREATE TABLE block, accumulates
    column definitions, lifts UNIQUE/KEY indexes out into separate CREATE INDEX
    statements (Postgres style), and converts enums to CHECK constraints.
    """
    sql = strip_mysql_comments(source_sql)
    sql = quote_identifiers(sql)

    output: list[str] = []
    output.append("-- ─────────────────────────────────────────────────────────────────")
    output.append("-- EIAAW Workforce — Postgres baseline schema")
    output.append("-- Translated from database/schema/mysql-schema.sql by")
    output.append("-- database/schema/translate_mysql_to_pgsql.py — DO NOT hand-edit;")
    output.append("-- if the source MySQL schema changes, re-run the translator.")
    output.append("-- ─────────────────────────────────────────────────────────────────")
    output.append("")

    pending_indexes: list[str] = []  # collected after each CREATE TABLE
    pending_fk_alters: list[str] = []  # ALL FKs deferred to end (Postgres FK targets must exist at create time)
    inside_table = False
    current_table = ""
    table_body: list[str] = []
    table_extras: list[str] = []  # CHECK constraints from enum→check, deferred
    table_fks: list[str] = []  # FK lines collected per table, hoisted to end
    auto_increment_col: str | None = None

    for raw_line in sql.split("\n"):
        line = raw_line.rstrip()

        # Skip MySQL session SET statements
        if SET_RE.match(line):
            continue
        # Skip DROP TABLE IF EXISTS (we use migrate:fresh anyway)
        if DROP_TABLE_RE.match(line):
            continue
        # Blank lines
        if not line.strip():
            if not inside_table:
                output.append("")
            continue

        # Start of a CREATE TABLE
        m = CREATE_TABLE_RE.match(line)
        if m:
            current_table = m.group(1)
            inside_table = True
            table_body = []
            table_extras = []
            table_fks = []
            auto_increment_col = None
            output.append(f'CREATE TABLE "{current_table}" (')
            continue

        # End of table
        if inside_table and TABLE_END_RE.match(line):
            # Emit the body lines, then the extras (CHECK constraints), close table
            for body_line in table_body[:-1]:
                output.append(body_line + ",")
            # last body line — may need a trailing comma if extras exist
            if table_extras:
                output.append(table_body[-1] + ",")
                for i, extra in enumerate(table_extras):
                    suffix = "," if i < len(table_extras) - 1 else ""
                    output.append("  " + extra + suffix)
            else:
                output.append(table_body[-1])
            output.append(");")
            output.append("")
            # Emit pending indexes for this table
            for idx in pending_indexes:
                output.append(idx)
            if pending_indexes:
                output.append("")
            pending_indexes = []
            inside_table = False
            continue

        if inside_table:
            stripped = line.strip().rstrip(",")

            # PRIMARY KEY
            pk = PRIMARY_KEY_RE.match(line)
            if pk:
                table_body.append(f"  PRIMARY KEY ({pk.group(1)})")
                continue

            # UNIQUE KEY → lift to a CREATE UNIQUE INDEX after the table
            uk = UNIQUE_KEY_RE.match(line)
            if uk:
                idx_name, cols = uk.group(1), uk.group(2)
                pending_indexes.append(
                    f'CREATE UNIQUE INDEX "{idx_name}" ON "{current_table}" ({cols});'
                )
                continue

            # KEY (regular index) → lift to CREATE INDEX. Skip indexes Postgres
            # auto-creates for FK constraints (named *_foreign), since those
            # are already covered by a btree index on the FK column on PG.
            k = KEY_RE.match(line)
            if k:
                idx_name, cols = k.group(1), k.group(2)
                if not idx_name.endswith("_foreign"):
                    pending_indexes.append(
                        f'CREATE INDEX "{idx_name}" ON "{current_table}" ({cols});'
                    )
                continue

            # CONSTRAINT ... FOREIGN KEY ...
            # Hoist to end-of-file as ALTER TABLE so referenced tables exist at FK creation time
            # (Postgres requires the target to exist; MySQL is permissive about FK ordering).
            if CONSTRAINT_FK_RE.match(line):
                pending_fk_alters.append(
                    f'ALTER TABLE "{current_table}" ADD {stripped};'
                )
                continue

            # Regular column definition — translate types
            translated = translate_column_types(line.rstrip(","))

            # Handle enum → CHECK constraint
            if re.search(r"\benum\(", translated, flags=re.IGNORECASE):
                new_def, check = translate_enum_to_check(current_table, translated)
                translated = new_def
                if check:
                    table_extras.append(check)

            table_body.append(translated)
            continue

        # Outside a table: pass through INSERT INTO migrations (with quoted ids)
        if INSERT_MIGRATIONS_RE.match(line):
            output.append(line)
            continue

    # Tail: emit all hoisted FK constraints now that every CREATE TABLE has run.
    if pending_fk_alters:
        output.append("")
        output.append("-- ─────────────────────────────────────────────────────────────────")
        output.append("-- Foreign keys (hoisted from inline CREATE TABLE so target tables exist)")
        output.append("-- ─────────────────────────────────────────────────────────────────")
        for alter in pending_fk_alters:
            output.append(alter)

    # Tail: re-align IDENTITY sequences for any table that received explicit-id
    # INSERTs above. Today only `migrations` does, but emit for completeness.
    output.append("")
    output.append("-- Realign IDENTITY sequences after explicit-id INSERTs above.")
    output.append(emit_sequence_resync("migrations"))
    output.append("")

    return "\n".join(output) + "\n"


def main() -> None:
    if not SOURCE.exists():
        raise SystemExit(f"Source not found: {SOURCE}")
    src = SOURCE.read_text(encoding="utf-8")
    out = translate(src)
    TARGET.write_text(out, encoding="utf-8")
    print(f"Wrote {TARGET} ({len(out.splitlines())} lines)")


if __name__ == "__main__":
    main()
